import type { Hackathon, WinnerProject } from "@/types";

export const HACKATHONS: Hackathon[] = [
  {
    id: "usaii-global-2026",
    title: "USAII® Global AI Hackathon 2026",
    organizer: "USAII",
    url: "https://usaii-global-ai-hackathon-2026.devpost.com/",
    deadline: "2026-06-21T23:59:00Z",
    prize_pool: "$15,000",
    theme: "AI Safety & Responsible AI",
    tech_tags: ["AI", "Machine Learning", "Ethics", "Python", "Any Stack"],
    team_size: "1–4",
    difficulty: "Intermediate",
    location: "Global · Virtual",
    summary: "Identify real-world risks in AI systems (bias, misinformation, misuse) and design solutions around them.",
    description: "Global hackathon where every team must identify a real-world AI risk and design mitigations. Separate tracks for High School, College, and Graduate levels with $5,000 prizes each.",
    status: "open",
    category: "AI / Machine Learning",
    participants: 2400,
    featured: true,
  },
  {
    id: "google-cloud-rapid-agents-2026",
    title: "Google Cloud Rapid Agent Hackathon",
    organizer: "Google Cloud",
    url: "https://rapid-agent.devpost.com/",
    deadline: "2026-06-25T23:59:00Z",
    prize_pool: "$30,000",
    theme: "Building AI Agents for Real-World Challenges",
    tech_tags: ["Gemini AI", "Google Cloud", "Agent AI", "Python", "Node.js"],
    team_size: "1–5",
    difficulty: "Advanced",
    location: "Global · Virtual",
    summary: "Build AI agents that solve real-world problems. Largest agent-focused hackathon of the year.",
    description: "Split into six partner-specific tracks, each awarding $5K (1st), $3K (2nd), $2K (3rd). Focus on autonomous agents powered by Gemini.",
    status: "open",
    category: "AI / Machine Learning",
    participants: 5200,
    featured: true,
  },
  {
    id: "developerweek-2026",
    title: "DeveloperWeek 2026 Hackathon",
    organizer: "DeveloperWeek",
    url: "https://developerweek-2026-hackathon.devpost.com/",
    deadline: "2026-06-20T23:59:00Z",
    prize_pool: "$12,500",
    theme: "Developer Tools & Productivity",
    tech_tags: ["Node.js", "Python", "AI/ML", "APIs", "DevTools"],
    team_size: "1–6",
    difficulty: "Intermediate",
    location: "San Francisco + Virtual",
    summary: "Nation's largest in-person + online hackathon. Multiple sponsor challenges with combined $12,500+ in prizes.",
    description: "Join 10,000+ developers at DeveloperWeek 2026. Build developer tools, AI applications, and solutions to sponsor challenges.",
    status: "open",
    category: "Developer Tools",
    participants: 3200,
    featured: true,
  },
  {
    id: "devnetwork-ai-ml-2026",
    title: "DevNetwork [AI + ML] Hackathon 2026",
    organizer: "DevNetwork",
    url: "https://devnetwork-ai-ml-hack-2026.devpost.com/",
    deadline: "2026-06-18T23:59:00Z",
    prize_pool: "$8,000",
    theme: "AI & Machine Learning Innovation",
    tech_tags: ["AI", "ML", "Python", "TensorFlow", "PyTorch"],
    team_size: "1–4",
    difficulty: "Intermediate",
    location: "Global · Virtual",
    summary: "Largest dedicated AI + ML hackathon challenge. Win Amazon Echos and DevNetwork premium access.",
    description: "Build cutting-edge AI/ML solutions. Winners get Amazon Echo devices, all-access conference passes, and featured announcement to 60,000+ subscribers.",
    status: "open",
    category: "AI / Machine Learning",
    participants: 1800,
    featured: true,
  },
  {
    id: "mind-the-product-2026",
    title: "Mind the Product: World Product Day 2026",
    organizer: "Mind the Product",
    url: "https://mindtheproduct.devpost.com/",
    deadline: "2026-06-20T23:59:00Z",
    prize_pool: "$2,000",
    theme: "Product Innovation with AI",
    tech_tags: ["Product", "AI", "Design", "Any Stack"],
    team_size: "1–5",
    difficulty: "All levels",
    location: "Global · Virtual",
    summary: "Ship a working AI-powered product. Judged on product thinking, craft, and shippedness.",
    description: "30-day hackathon emphasizing real product execution. Requires Novus.ai analytics integration. Scored on Product Thinking (25%), Craft (25%), Originality (25%), and Shippedness (25%).",
    status: "open",
    category: "Product Innovation",
    participants: 1200,
    featured: true,
  },
  {
    id: "hack-devpost-2026",
    title: "Hack Devpost 2026",
    organizer: "Devpost",
    url: "https://hackdevpost.devpost.com/",
    deadline: "2026-06-12T23:59:00Z",
    prize_pool: "$12,000",
    theme: "Build Tools for Hackathon Communities",
    tech_tags: ["React", "Node.js", "AI", "UX", "APIs"],
    team_size: "1–4",
    difficulty: "All levels",
    location: "Global · Virtual",
    summary: "Build products that improve how hackathons run, discoveries work, or communities form.",
    description: "Meta hackathon: create tools that make hackathons better for participants, organizers, and judges. Devpost opens its platform as the challenge.",
    status: "closing_soon",
    category: "Developer Tools",
    participants: 750,
  },
  {
    id: "produhacks-2026",
    title: "ProduHacks 2026: Built to Last",
    organizer: "ProduHacks",
    url: "https://produhacks-2026.devpost.com/",
    deadline: "2026-07-15T23:59:00Z",
    prize_pool: "$8,000",
    theme: "Products That Matter",
    tech_tags: ["Product Design", "AI", "Mobile", "Web"],
    team_size: "2–4",
    difficulty: "Beginner",
    location: "Global · Virtual",
    summary: "Build products with genuine staying power — solving real problems, not just clever demos.",
    description: "ProduHacks prioritizes real user value, sustainable business models, and thoughtful design. Judges value builders who ship products people actually use.",
    status: "upcoming",
    category: "Product Innovation",
    participants: 420,
  },
  {
    id: "openai-open-model-2026",
    title: "OpenAI Open Model Hackathon 2026",
    organizer: "OpenAI + Hugging Face + NVIDIA",
    url: "https://openai.devpost.com/",
    deadline: "2026-07-31T23:59:00Z",
    prize_pool: "$25,000",
    theme: "Creative Applications of Open Models",
    tech_tags: ["GPT-OSS", "Reasoning Models", "LLM", "Python", "Hardware"],
    team_size: "1–4",
    difficulty: "Intermediate",
    location: "Global · Virtual",
    summary: "6-week hackathon: Build robots with reasoning, offline agents, fine-tuned models, or push hardware to the edge.",
    description: "Apply OpenAI's open-weight reasoning models in creative, unexpected ways. Collaborate with Hugging Face, NVIDIA, Ollama, vLLM, LM Studio. For all technical levels.",
    status: "open",
    category: "AI / Machine Learning",
    participants: 3500,
  },
];

export const WINNER_PROJECTS: WinnerProject[] = [
  {
    id: "w1",
    hackathon_title: "World Wide Vibes Hackathon",
    hackathon_year: 2026,
    project_name: "Market-Gap AI",
    prize_won: "3rd Place — $750",
    tech_stack: ["Next.js", "Python", "Bright Data", "OpenAI", "Supabase"],
    description: "AI-powered market intelligence that shows entrepreneurs exactly where to open their next business.",
    url: "https://market-gap-ai-production.up.railway.app/",
    insight: "Won by combining real geospatial data with AI narrative — judges loved the instant actionability.",
  },
  {
    id: "w2",
    hackathon_title: "Google AI Hackathon 2025",
    hackathon_year: 2025,
    project_name: "Flora AI",
    prize_won: "1st Place — $10,000",
    tech_stack: ["React", "Python", "Gemini", "RAG", "FastAPI"],
    description: "AI that reads financial documents and SEC filings, answering questions with live citations across your entire document library.",
    url: "https://devpost.com/software/flora-ai",
    insight: "RAG over real documents beats generic chatbots — judges love when AI cites its source mid-answer.",
  },
  {
    id: "w3",
    hackathon_title: "Google Chrome Built-in AI Challenge 2025",
    hackathon_year: 2025,
    project_name: "MailMate AI",
    prize_won: "Top Prize — $3,000",
    tech_stack: ["Chrome Extension", "Chrome Built-in AI", "JavaScript", "Gemini Nano"],
    description: "Chrome extension that summarizes, drafts, and manages Gmail with one click — tone customization built in.",
    url: "https://devpost.com/software/ai-asistant-for-gmail",
    insight: "Chrome Extension + AI combo wins micro-SaaS brackets almost every time. Zero-friction UX is king.",
  },
  {
    id: "w4",
    hackathon_title: "Healthcare AI Hackathon 2025",
    hackathon_year: 2025,
    project_name: "SymptoCheck",
    prize_won: "1st Place — $25,000",
    tech_stack: ["React Native", "TensorFlow", "Python", "Firebase"],
    description: "Mobile symptom checker that triages patient conditions using AI — bridging the gap between patients and care providers.",
    url: "https://devpost.com/software/symptocheck",
    insight: "Healthcare AI winners always solve the last mile — easy data input + clear output for non-technical users.",
  },
  {
    id: "w5",
    hackathon_title: "Hack Devpost 2025",
    hackathon_year: 2025,
    project_name: "HackMate",
    prize_won: "2nd Place — $5,000",
    tech_stack: ["Next.js", "OpenAI", "Supabase", "Railway"],
    description: "AI hackathon companion that generates project ideas, professional READMEs, and pitch decks from a single prompt.",
    url: "https://devpost.com/software/hackmate-3brfmx",
    insight: "Meta-hackathon tools (tools for hackers) punch above their weight with judges who get the irony.",
  },
  {
    id: "w6",
    hackathon_title: "Web3 Builder Hackathon 2025",
    hackathon_year: 2025,
    project_name: "Smart Contract Scan",
    prize_won: "1st Place — $15,000",
    tech_stack: ["Solidity", "Python", "GPT-4", "Hardhat", "React"],
    description: "AI that audits Solidity smart contracts and generates plain-English security reports — results locked onchain.",
    url: "https://devpost.com/software/smart-contract-scan",
    insight: "Web3 + AI safety is the hottest combo right now — anything that reduces audit costs wins big.",
  },
];

export const CATEGORIES = [
  "All",
  "AI / Machine Learning",
  "Product Innovation",
  "Developer Tools",
  "Web3 + Privacy",
  "FinTech / Economics",
  "AI / Customer Experience",
];

export const TECH_TAGS = [
  "AI", "Python", "React", "Next.js", "Web3", "Gemini AI",
  "Node.js", "Supabase", "Chrome Extension", "Mobile", "APIs",
];

export const AI_INSIGHTS = [
  "🏆 Chrome Extension + AI combos win Micro-SaaS brackets ~70% of the time",
  "📊 Projects with live demos beat static screenshots by 3x in judging scores",
  "🚀 Gemini Flash is the fastest free AI for hackathon summarization tasks",
  "💡 'Meta' tools (tools for hackers, submitted to hackathons) score high on originality",
  "⚡ Have a live, working URL that judges can click. That&apos;s what matters most.",
  "🎯 Healthcare AI winners always solve last-mile UX, not just model accuracy",
];
