import type { Hackathon, WinnerProject } from "@/types";

export const HACKATHONS: Hackathon[] = [
  {
    id: "mind-the-product-2026",
    title: "World Product Day: Everyone Ships Now",
    organizer: "Mind the Product",
    url: "https://mindtheproduct.devpost.com/",
    deadline: "2026-06-15T23:59:00Z",
    prize_pool: "$2,000",
    theme: "Product Innovation with AI",
    tech_tags: ["AI", "Product", "Novus.ai", "Any Stack"],
    team_size: "1–5",
    difficulty: "All levels",
    location: "Global · Virtual",
    summary: "Ship a working AI-powered product in 30 days — judged on product thinking, craft, and shippedness.",
    description: "30-day hackathon where PMs, designers, and engineers build and ship real AI products. Must have Novus.ai installed. Judged on Product Thinking, Craft & Execution, Originality, and Shippedness.",
    status: "open",
    category: "Product Innovation",
    participants: 1200,
    featured: true,
  },
  {
    id: "build-gemini-xprize-2026",
    title: "Build with Gemini XPRIZE",
    organizer: "Google + XPRIZE",
    url: "https://xprize.devpost.com/",
    deadline: "2026-07-01T23:59:00Z",
    prize_pool: "$2,000,000",
    theme: "World-Impact Products with Gemini",
    tech_tags: ["Gemini AI", "Google Cloud", "Python", "React"],
    team_size: "1–4",
    difficulty: "Advanced",
    location: "Global · Virtual",
    summary: "Build world-changing AI products with Google Gemini — $2M prize pool up for grabs.",
    description: "XPRIZE and Google challenge teams to build impactful products powered by Gemini AI. Focus on products that address real-world problems at scale.",
    status: "open",
    category: "AI / Machine Learning",
    participants: 8500,
    featured: true,
  },
  {
    id: "developerweek-2026",
    title: "DeveloperWeek 2026 Hackathon",
    organizer: "DeveloperWeek",
    url: "https://developerweek-2026-hackathon.devpost.com/",
    deadline: "2026-06-20T23:59:00Z",
    prize_pool: "$15,000",
    theme: "Developer Tools & AI Automation",
    tech_tags: ["Node.js", "Python", "AI/ML", "APIs", "DevTools"],
    team_size: "1–6",
    difficulty: "Intermediate",
    location: "San Francisco + Virtual",
    summary: "Nation's largest in-person + online hackathon focused on AI-powered developer tooling.",
    description: "DeveloperWeek brings together 10,000+ developers for the world's largest developer conference and hackathon. Build tools that make developers more productive.",
    status: "open",
    category: "Developer Tools",
    participants: 3200,
    featured: true,
  },
  {
    id: "midnight-hackathon-2026",
    title: "Midnight Hackathon",
    organizer: "Midnight Network",
    url: "https://midnight-hackathon-2026.devpost.com/",
    deadline: "2026-06-10T23:59:00Z",
    prize_pool: "$50,000",
    theme: "Privacy-First Web3 Applications",
    tech_tags: ["Web3", "Blockchain", "Privacy", "Rust", "TypeScript"],
    team_size: "1–4",
    difficulty: "Advanced",
    location: "Global · Virtual",
    summary: "Build privacy-preserving applications on Midnight's zero-knowledge blockchain network.",
    description: "Build on a fully launched network designed to solve the internet's biggest privacy challenges using zero-knowledge proofs and confidential smart contracts.",
    status: "closing_soon",
    category: "Web3 + Privacy",
    participants: 640,
  },
  {
    id: "cxc-2026-ai",
    title: "CXC 2026 — AI Hackathon",
    organizer: "CXC",
    url: "https://cxc-2026-ai-hackathon.devpost.com/",
    deadline: "2026-06-28T23:59:00Z",
    prize_pool: "$10,000",
    theme: "AI for Customer Experience",
    tech_tags: ["AI", "LLM", "Python", "React", "APIs"],
    team_size: "1–5",
    difficulty: "Intermediate",
    location: "Global · Virtual",
    summary: "36-hour AI hackathon focused on transforming customer experience through intelligent automation.",
    description: "CXC is back with a fresh AI spin — 36 hours of hacking, networking, and big prizes for the best AI-powered customer experience products.",
    status: "open",
    category: "AI / Customer Experience",
    participants: 890,
  },
  {
    id: "produhacks-2026",
    title: "ProduHacks 2026: Built to Last",
    organizer: "ProduHacks",
    url: "https://produhacks-2026.devpost.com/",
    deadline: "2026-07-15T23:59:00Z",
    prize_pool: "$8,000",
    theme: "Products That Matter",
    tech_tags: ["Product Design", "AI", "Mobile", "Web"],
    team_size: "2–4",
    difficulty: "Beginner",
    location: "Global · Virtual",
    summary: "Build products that solve real, lasting problems — not just clever demos that nobody uses.",
    description: "ProduHacks challenges builders to create products with genuine staying power. Judges prioritize real user value, sustainable business models, and thoughtful design.",
    status: "upcoming",
    category: "Product Innovation",
    participants: 420,
  },
  {
    id: "hackonomics-2026",
    title: "Hackonomics 2026",
    organizer: "Hackonomics",
    url: "https://hackonomics26.devpost.com/",
    deadline: "2026-07-30T23:59:00Z",
    prize_pool: "$5,000",
    theme: "Computer Science + Economics",
    tech_tags: ["Python", "Data Science", "ML", "Economics", "Finance"],
    team_size: "1–3",
    difficulty: "Intermediate",
    location: "Global · Virtual",
    summary: "Where computer science meets economics — build AI tools that analyze markets and financial systems.",
    description: "Hackonomics bridges CS and economics education, helping participants build insight into how computational tools can model, predict, and improve economic systems.",
    status: "upcoming",
    category: "FinTech / Economics",
    participants: 310,
  },
  {
    id: "hack-devpost-2026",
    title: "Hack Devpost",
    organizer: "Devpost",
    url: "https://hackdevpost.devpost.com/",
    deadline: "2026-06-05T23:59:00Z",
    prize_pool: "$12,000",
    theme: "Improve the Hackathon Experience",
    tech_tags: ["React", "Node.js", "AI", "UX", "APIs"],
    team_size: "1–4",
    difficulty: "All levels",
    location: "Global · Virtual",
    summary: "Build tools that make hackathons better for participants, organizers, and judges.",
    description: "Devpost opens its own platform as a challenge: build products that improve how hackathons run, how projects are discovered, or how communities form around hackathons.",
    status: "closing_soon",
    category: "Developer Tools",
    participants: 750,
  },
];

export const WINNER_PROJECTS: WinnerProject[] = [
  {
    id: "w1",
    hackathon_title: "World Wide Vibes Hackathon",
    hackathon_year: 2026,
    project_name: "Market-Gap AI",
    prize_won: "3rd Place — $750",
    tech_stack: ["Next.js", "Python", "Bright Data", "OpenAI", "Supabase"],
    description: "AI-powered market intelligence that shows entrepreneurs exactly where to open their next business.",
    url: "https://market-gap-ai-production.up.railway.app/",
    insight: "Won by combining real geospatial data with AI narrative — judges loved the instant actionability.",
  },
  {
    id: "w2",
    hackathon_title: "Google AI Hackathon 2025",
    hackathon_year: 2025,
    project_name: "Flora AI",
    prize_won: "1st Place — $10,000",
    tech_stack: ["React", "Python", "Gemini", "RAG", "FastAPI"],
    description: "AI that reads financial documents and SEC filings, answering questions with live citations across your entire document library.",
    url: "https://devpost.com/software/flora-ai",
    insight: "RAG over real documents beats generic chatbots — judges love when AI cites its source mid-answer.",
  },
  {
    id: "w3",
    hackathon_title: "Google Chrome Built-in AI Challenge 2025",
    hackathon_year: 2025,
    project_name: "MailMate AI",
    prize_won: "Top Prize — $3,000",
    tech_stack: ["Chrome Extension", "Chrome Built-in AI", "JavaScript", "Gemini Nano"],
    description: "Chrome extension that summarizes, drafts, and manages Gmail with one click — tone customization built in.",
    url: "https://devpost.com/software/ai-asistant-for-gmail",
    insight: "Chrome Extension + AI combo wins micro-SaaS brackets almost every time. Zero-friction UX is king.",
  },
  {
    id: "w4",
    hackathon_title: "Healthcare AI Hackathon 2025",
    hackathon_year: 2025,
    project_name: "SymptoCheck",
    prize_won: "1st Place — $25,000",
    tech_stack: ["React Native", "TensorFlow", "Python", "Firebase"],
    description: "Mobile symptom checker that triages patient conditions using AI — bridging the gap between patients and care providers.",
    url: "https://devpost.com/software/symptocheck",
    insight: "Healthcare AI winners always solve the last mile — easy data input + clear output for non-technical users.",
  },
  {
    id: "w5",
    hackathon_title: "Hack Devpost 2025",
    hackathon_year: 2025,
    project_name: "HackMate",
    prize_won: "2nd Place — $5,000",
    tech_stack: ["Next.js", "OpenAI", "Supabase", "Vercel"],
    description: "AI hackathon companion that generates project ideas, professional READMEs, and pitch decks from a single prompt.",
    url: "https://devpost.com/software/hackmate-3brfmx",
    insight: "Meta-hackathon tools (tools for hackers) punch above their weight with judges who get the irony.",
  },
  {
    id: "w6",
    hackathon_title: "Web3 Builder Hackathon 2025",
    hackathon_year: 2025,
    project_name: "Smart Contract Scan",
    prize_won: "1st Place — $15,000",
    tech_stack: ["Solidity", "Python", "GPT-4", "Hardhat", "React"],
    description: "AI that audits Solidity smart contracts and generates plain-English security reports — results locked onchain.",
    url: "https://devpost.com/software/smart-contract-scan",
    insight: "Web3 + AI safety is the hottest combo right now — anything that reduces audit costs wins big.",
  },
];

export const CATEGORIES = [
  "All",
  "AI / Machine Learning",
  "Product Innovation",
  "Developer Tools",
  "Web3 + Privacy",
  "FinTech / Economics",
  "AI / Customer Experience",
];

export const TECH_TAGS = [
  "AI", "Python", "React", "Next.js", "Web3", "Gemini AI",
  "Node.js", "Supabase", "Chrome Extension", "Mobile", "APIs",
];

export const AI_INSIGHTS = [
  "🏆 Chrome Extension + AI combos win Micro-SaaS brackets ~70% of the time",
  "📊 Projects with live demos beat static screenshots by 3x in judging scores",
  "🚀 Gemini Flash is the fastest free AI for hackathon summarization tasks",
  "💡 'Meta' tools (tools for hackers, submitted to hackathons) score high on originality",
  "⚡ Vercel + Next.js = fastest path from code to live URL — judges can actually click it",
  "🎯 Healthcare AI winners always solve last-mile UX, not just model accuracy",
];
