-- Add 12 more AI/ML hackathons to expand the directory
-- Run this in Supabase SQL Editor

INSERT INTO public.hackathons (id, title, organizer, url, deadline, prize_pool, theme, tech_tags, team_size, difficulty, location, summary, description, status, category, participants, featured)
VALUES
  ('ai-devfest-2026', 'AI DevFest 2026', 'Google AI', 'https://aidevfest.devpost.com/', '2026-06-30T23:59:00Z', '$20,000', 'AI Innovation & Development', ARRAY['TensorFlow','PyTorch','Gemini','Python','Google Cloud'], '1–6', 'Intermediate', 'Global · Virtual', 'Build next-gen AI applications powered by Google Cloud and TensorFlow.', 'Google AI DevFest: showcase your AI/ML skills on Google Cloud infrastructure. Integrated Gemini AI tooling. Beginner-friendly workshops included.', 'open', 'AI / Machine Learning', 4100, true),

  ('mlh-global-hack-week-ai', 'MLH Global Hack Week: AI/ML', 'Major League Hacking', 'https://ghw.mlh.com/events', '2026-08-15T23:59:00Z', '$5,000', 'Monthly AI/ML Challenges', ARRAY['AI','Machine Learning','Python','TensorFlow','PyTorch'], '1–4', 'Beginner', 'Global · Virtual', 'Complete daily AI/ML challenges and build your portfolio with the MLH community.', 'MLH Global Hack Week: AI edition. Participate in daily challenges, attend workshops, and compete for prizes. Great for building your AI portfolio.', 'open', 'AI / Machine Learning', 6500, true),

  ('facebook-llm-hackathon-2026', 'Meta LLM Hackathon 2026', 'Meta AI', 'https://meta-llm-hack.devpost.com/', '2026-07-10T23:59:00Z', '$35,000', 'Large Language Model Applications', ARRAY['LLM','Llama','Python','NLP','Fine-tuning'], '2–5', 'Advanced', 'Global · Virtual', 'Build powerful applications with Meta''s Llama models and AI infrastructure.', 'Meta LLM Hackathon: build with Llama 3 and Meta''s open-source AI stack. Advanced track for production-ready systems. API credits included.', 'open', 'AI / Machine Learning', 3800, true),

  ('mlh-hack-days-roborregos', 'MLH HackDays by RoBorregos 2026', 'RoBorregos', 'https://hackdays-by-roborregos-2026.devpost.com/', '2026-06-22T23:59:00Z', '$8,000', 'AI-Powered Mini Hackathons', ARRAY['Gemini','Google Cloud','Python','AI','Robotics'], '1–3', 'Beginner', 'San Francisco · In-Person', '12-hour sprint using Google Gemini to build AI-powered solutions.', 'Mini hackathon format: 12 hours to build with Gemini AI. Perfect for beginners. In-person at South San Francisco. Free food and mentorship.', 'open', 'AI / Machine Learning', 280, false),

  ('stanford-ai-summit-hack', 'Stanford AI Summit Hackathon 2026', 'Stanford University', 'https://stanford-ai-summit.devpost.com/', '2026-07-20T23:59:00Z', '$18,000', 'Academic AI Research + Applications', ARRAY['AI Research','Machine Learning','Python','Academia','Innovation'], '1–5', 'Advanced', 'Palo Alto · In-Person', 'Collaborate with Stanford researchers on cutting-edge AI applications.', 'Stanford AI Summit: bring your AI ideas to Stanford campus. Network with top researchers. Focus on ethics, safety, and real-world impact.', 'open', 'AI / Machine Learning', 1500, true),

  ('nvidia-ai-challenge-2026', 'NVIDIA AI Challenge 2026', 'NVIDIA', 'https://nvidia-ai-challenge.devpost.com/', '2026-07-25T23:59:00Z', '$40,000', 'GPU-Accelerated AI Systems', ARRAY['CUDA','GPU','Deep Learning','Python','NVIDIA Cloud'], '1–6', 'Advanced', 'Global · Virtual', 'Build high-performance AI systems optimized for NVIDIA GPUs.', 'NVIDIA AI Challenge: access free GPU credits and CUDA toolkit. Build models that scale. Advanced developers. Community recognition for top projects.', 'open', 'AI / Machine Learning', 2900, true),

  ('anthropic-claude-hackathon', 'Anthropic Claude Hackathon 2026', 'Anthropic', 'https://anthropic-claude-hack.devpost.com/', '2026-08-05T23:59:00Z', '$25,000', 'Building with Claude API', ARRAY['Claude','LLM','Python','Node.js','API'], '1–5', 'Intermediate', 'Global · Virtual', 'Create innovative applications using the Claude API and prompt engineering.', 'Anthropic Claude Hackathon: free Claude API credits, dedicated support channel. Build assistants, agents, and LLM-powered tools. Beginner-friendly.', 'open', 'AI / Machine Learning', 2200, true),

  ('hugging-face-community-jam', 'Hugging Face Community Jam 2026', 'Hugging Face', 'https://hf-community-jam.devpost.com/', '2026-07-31T23:59:00Z', '$12,000', 'Open-Source ML Community', ARRAY['Transformers','Datasets','Hugging Face','Python','NLP'], '1–4', 'Beginner', 'Global · Virtual', 'Contribute to open-source ML projects with the Hugging Face community.', 'Hugging Face Community Jam: build with transformers and datasets. No experience needed. Community voting determines winners. Showcase your work globally.', 'open', 'AI / Machine Learning', 1400, false),

  ('aws-ai-ml-summit-hack', 'AWS AI/ML Summit Hackathon 2026', 'Amazon Web Services', 'https://aws-ai-ml-hack.devpost.com/', '2026-06-28T23:59:00Z', '$16,000', 'AWS AI Services & SageMaker', ARRAY['SageMaker','AWS','Machine Learning','Python','Cloud'], '1–5', 'Intermediate', 'Global · Virtual', 'Build AI solutions using AWS SageMaker and managed ML services.', 'AWS AI/ML Hackathon: free SageMaker credits, pre-built models, tutorials. Perfect for those new to cloud ML. AWS experts available for guidance.', 'open', 'AI / Machine Learning', 2600, true),

  ('ai-safety-alignment-hackathon', 'AI Safety & Alignment Hackathon 2026', 'Center for AI Safety', 'https://ai-safety-hack.devpost.com/', '2026-08-10T23:59:00Z', '$10,000', 'Responsible AI & Safety Research', ARRAY['AI Safety','Ethics','Alignment','Research','Python'], '1–4', 'Advanced', 'Global · Virtual', 'Research and develop solutions for AI safety and alignment challenges.', 'AI Safety Hackathon: focus on interpretability, robustness, and alignment. Research-oriented. Academic mentorship. Published in relevant journals.', 'open', 'AI / Machine Learning', 950, true),

  ('startup-ai-pitch-hack', 'Startup AI Pitch Hackathon 2026', 'Y Combinator Partners', 'https://startup-ai-pitch.devpost.com/', '2026-08-01T23:59:00Z', '$15,000', 'Turning AI Ideas Into Startups', ARRAY['Startups','AI','Pitch','Business','Fundraising'], '2–5', 'All levels', 'Global · Virtual', 'Build an AI startup concept in 48 hours and pitch to investors.', 'Startup AI Pitch: focus on business model, not just code. Pitch to YC-connected investors. Winners get follow-up mentor sessions. Demo day format.', 'upcoming', 'AI / Machine Learning', 650, false),

  ('mlh-ghw-blockchain-ai', 'Global Hack Week: Blockchain + AI 2026', 'MLH', 'https://ghw-blockchain-ai.devpost.com/', '2026-07-28T23:59:00Z', '$6,000', 'Decentralized AI Applications', ARRAY['Blockchain','AI','Web3','Smart Contracts','Python'], '1–4', 'Advanced', 'Global · Virtual', 'Build decentralized AI applications combining blockchain and machine learning.', 'Global Hack Week: Blockchain + AI edition. Explore DeFi + AI opportunities. Learn Solidity and LLMs. Community-driven judging. Great networking.', 'open', 'AI / Machine Learning', 520, false);

-- Verify insertion
SELECT COUNT(*) as total_hackathons FROM public.hackathons;
